# Generated by Django 4.1.5 on 2023-01-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="importnace",
            new_name="priority",
        ),
    ]
