# Generated by Django 4.1.5 on 2023-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_rename_importnace_todo_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="date",
            field=models.DateTimeField(default="2023-01-25"),
            preserve_default=False,
        ),
    ]
